-- SELECT FIRST_NAME, LAST_NAME
-- FROM EMPLOYEES
-- WHERE ADDRESS LIKE '%Elgin,IL%';

-- SELECT FIRST_NAME, LAST_NAME
-- FROM EMPLOYEES
-- WHERE BIRTH_DATE LIKE '197%';

-- SELECT *
-- FROM EMPLOYEES
-- WHERE (SALARY BETWEEN 60000 AND 70000) AND DEPT_ID = 5;

-- SELECT FIRST_NAME, LAST_NAME, DEPT_ID 
-- FROM EMPLOYEES
-- ORDER BY DEPT_ID;

-- SELECT FIRST_NAME, LAST_NAME, DEPT_ID 
-- FROM EMPLOYEES
-- ORDER BY DEPT_ID;

-- SELECT DEPT_ID, COUNT(*)
-- FROM EMPLOYEES
-- GROUP BY DEPT_ID;

-- SELECT DEPT_ID, COUNT(*), AVG(SALARY)
-- FROM EMPLOYEES
-- GROUP BY DEPT_ID;

-- SELECT DEPT_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
-- FROM EMPLOYEES
-- GROUP BY DEPT_ID;

-- SELECT DEPT_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
-- FROM EMPLOYEES
-- GROUP BY DEPT_ID
-- ORDER BY AVG_SALARY;

-- SELECT DEPT_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
-- FROM EMPLOYEES
-- GROUP BY DEPT_ID
-- HAVING count(*) < 4
-- ORDER BY AVG_SALARY;

-- PRACTICE QUESTIONS

-- SELECT FIRST_NAME, LAST_NAME
-- FROM EMPLOYEES
-- WHERE FIRST_NAME LIKE 'S%';

-- SELECT *
-- FROM EMPLOYEES
-- ORDER BY BIRTH_DATE;

-- SELECT DEPT_ID, AVG(SALARY)
-- FROM EMPLOYEES
-- GROUP BY DEPT_ID
-- HAVING AVG(SALARY) >= 60000;

-- SELECT DEPT_ID, AVG(SALARY)
-- FROM EMPLOYEES
-- GROUP BY DEPT_ID
-- HAVING AVG(SALARY) >= 60000;