-- USE HR;

-- SELECT * FROM EMPLOYEES WHERE JOB_ID IN (SELECT JOB_ID FROM JOBS);

-- SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, JOB_ID
-- FROM JOBS
-- WHERE JOB_ID IN (select JOB_ID from EMPLOYEES where SALARY > 70000 );

-- SELECT *
-- FROM EMPLOYEES, JOBS
-- WHERE EMPLOYEES.JOB_ID = JOBS.JOB_ID;

-- SELECT *
-- FROM EMPLOYEES E, JOBS J
-- WHERE E.JOB_ID = J.JOB_ID;

-- SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME, JOB_TITLE
-- FROM EMPLOYEES E, JOBS J
-- WHERE E.JOB_ID = J.JOB_ID;

-- SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE
-- FROM EMPLOYEES E, JOBS J
-- WHERE E.JOB_ID = J.JOB_ID;

-- SELECT *
-- FROM EMPLOYEES
-- WHERE JOB_ID IN (SELECT JOB_ID
--                  FROM JOBS
--                  WHERE JOB_TITLE= 'Jr. Designer');

-- SELECT *
-- FROM EMPLOYEES E, JOBS J
-- WHERE E.JOB_ID = J.JOB_ID AND J.JOB_TITLE= 'Jr. Designer';

-- SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, JOB_ID
-- FROM JOBS
-- WHERE JOB_ID IN (SELECT JOB_ID
--                     FROM EMPLOYEES
--                     WHERE YEAR(BIRTH_DATE)>1976 );

-- SELECT J.JOB_TITLE, J.MIN_SALARY, J.MAX_SALARY, J.JOB_ID
-- FROM JOBS J, EMPLOYEES E
-- WHERE E.JOB_ID = J.JOB_ID AND YEAR(E.BIRTH_DATE)>1976;