-- USE HR;

-- SELECT * 
-- FROM EMPLOYEES 
-- WHERE salary < AVG(salary); # This will not work as expected because AVG(SALARY) is an aggregate function and cannot be used directly in the WHERE clause.

-- SELECT *
-- FROM EMPLOYEES
-- WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

-- SELECT EMPLOYEE_ID, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY 
-- FROM EMPLOYEES;

-- SELECT FIRST_NAME, LAST_NAME
-- FROM EMPLOYEES
-- WHERE BIRTH_DATE = (SELECT MIN(BIRTH_DATE) FROM EMPLOYEES);

-- SELECT AVG(SALARY) 
-- FROM (SELECT SALARY 
--       FROM EMPLOYEES 
--       ORDER BY SALARY DESC 
--       LIMIT 5) AS SALARY_TABLE;

-- **PRACTICE PROBLEMS**

-- SELECT AVG(SALARY) 
-- FROM (SELECT SALARY 
--       FROM EMPLOYEES 
--       ORDER BY SALARY 
--       LIMIT 5) AS SALARY_TABLE;

-- SELECT * 
-- FROM EMPLOYEES 
-- WHERE YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE,BIRTH_DATE))) > 
--     (SELECT AVG(YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE,BIRTH_DATE)))) 
--     FROM EMPLOYEES);

-- SELECT EMPLOYEE_ID, YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE, START_DATE))), 
--     (SELECT AVG(YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE, START_DATE)))) 
--     FROM JOB_HISTORY)
-- FROM JOB_HISTORY;